// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceAuthClient creates a new instance of MockServiceAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceAuthClient {
	mock := &MockServiceAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceAuthClient is an autogenerated mock type for the ServiceAuthClient type
type MockServiceAuthClient struct {
	mock.Mock
}

type MockServiceAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceAuthClient) EXPECT() *MockServiceAuthClient_Expecter {
	return &MockServiceAuthClient_Expecter{mock: &_m.Mock}
}

// GetAuthToken provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) GetAuthToken(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthToken")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceAuthClient_GetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthToken'
type MockServiceAuthClient_GetAuthToken_Call struct {
	*mock.Call
}

// GetAuthToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceAuthClient_Expecter) GetAuthToken(ctx interface{}) *MockServiceAuthClient_GetAuthToken_Call {
	return &MockServiceAuthClient_GetAuthToken_Call{Call: _e.mock.On("GetAuthToken", ctx)}
}

func (_c *MockServiceAuthClient_GetAuthToken_Call) Run(run func(ctx context.Context)) *MockServiceAuthClient_GetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_GetAuthToken_Call) Return(s *string, err error) *MockServiceAuthClient_GetAuthToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockServiceAuthClient_GetAuthToken_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockServiceAuthClient_GetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestTokenClaimsFromGinContext provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) GetRequestTokenClaimsFromGinContext(gc *gin.Context) (*TokenClaims, error) {
	ret := _mock.Called(gc)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestTokenClaimsFromGinContext")
	}

	var r0 *TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) (*TokenClaims, error)); ok {
		return returnFunc(gc)
	}
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) *TokenClaims); ok {
		r0 = returnFunc(gc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = returnFunc(gc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestTokenClaimsFromGinContext'
type MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call struct {
	*mock.Call
}

// GetRequestTokenClaimsFromGinContext is a helper method to define mock.On call
//   - gc *gin.Context
func (_e *MockServiceAuthClient_Expecter) GetRequestTokenClaimsFromGinContext(gc interface{}) *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call {
	return &MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call{Call: _e.mock.On("GetRequestTokenClaimsFromGinContext", gc)}
}

func (_c *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call) Run(run func(gc *gin.Context)) *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call) Return(tokenClaims *TokenClaims, err error) *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call) RunAndReturn(run func(gc *gin.Context) (*TokenClaims, error)) *MockServiceAuthClient_GetRequestTokenClaimsFromGinContext_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPClient provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) HTTPClient() *http.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTPClient")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// MockServiceAuthClient_HTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPClient'
type MockServiceAuthClient_HTTPClient_Call struct {
	*mock.Call
}

// HTTPClient is a helper method to define mock.On call
func (_e *MockServiceAuthClient_Expecter) HTTPClient() *MockServiceAuthClient_HTTPClient_Call {
	return &MockServiceAuthClient_HTTPClient_Call{Call: _e.mock.On("HTTPClient")}
}

func (_c *MockServiceAuthClient_HTTPClient_Call) Run(run func()) *MockServiceAuthClient_HTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceAuthClient_HTTPClient_Call) Return(client *http.Client) *MockServiceAuthClient_HTTPClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockServiceAuthClient_HTTPClient_Call) RunAndReturn(run func() *http.Client) *MockServiceAuthClient_HTTPClient_Call {
	_c.Call.Return(run)
	return _c
}

// Middleware provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) Middleware(requiredPerms Permissions) gin.HandlerFunc {
	ret := _mock.Called(requiredPerms)

	if len(ret) == 0 {
		panic("no return value specified for Middleware")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(Permissions) gin.HandlerFunc); ok {
		r0 = returnFunc(requiredPerms)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockServiceAuthClient_Middleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Middleware'
type MockServiceAuthClient_Middleware_Call struct {
	*mock.Call
}

// Middleware is a helper method to define mock.On call
//   - requiredPerms Permissions
func (_e *MockServiceAuthClient_Expecter) Middleware(requiredPerms interface{}) *MockServiceAuthClient_Middleware_Call {
	return &MockServiceAuthClient_Middleware_Call{Call: _e.mock.On("Middleware", requiredPerms)}
}

func (_c *MockServiceAuthClient_Middleware_Call) Run(run func(requiredPerms Permissions)) *MockServiceAuthClient_Middleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Permissions
		if args[0] != nil {
			arg0 = args[0].(Permissions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_Middleware_Call) Return(handlerFunc gin.HandlerFunc) *MockServiceAuthClient_Middleware_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockServiceAuthClient_Middleware_Call) RunAndReturn(run func(requiredPerms Permissions) gin.HandlerFunc) *MockServiceAuthClient_Middleware_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceAuthClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockServiceAuthClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceAuthClient_Expecter) Ping(ctx interface{}) *MockServiceAuthClient_Ping_Call {
	return &MockServiceAuthClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockServiceAuthClient_Ping_Call) Run(run func(ctx context.Context)) *MockServiceAuthClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_Ping_Call) Return(err error) *MockServiceAuthClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceAuthClient_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockServiceAuthClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RequireScopes provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) RequireScopes(required Scopes) gin.HandlerFunc {
	ret := _mock.Called(required)

	if len(ret) == 0 {
		panic("no return value specified for RequireScopes")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func(Scopes) gin.HandlerFunc); ok {
		r0 = returnFunc(required)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockServiceAuthClient_RequireScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireScopes'
type MockServiceAuthClient_RequireScopes_Call struct {
	*mock.Call
}

// RequireScopes is a helper method to define mock.On call
//   - required Scopes
func (_e *MockServiceAuthClient_Expecter) RequireScopes(required interface{}) *MockServiceAuthClient_RequireScopes_Call {
	return &MockServiceAuthClient_RequireScopes_Call{Call: _e.mock.On("RequireScopes", required)}
}

func (_c *MockServiceAuthClient_RequireScopes_Call) Run(run func(required Scopes)) *MockServiceAuthClient_RequireScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Scopes
		if args[0] != nil {
			arg0 = args[0].(Scopes)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_RequireScopes_Call) Return(handlerFunc gin.HandlerFunc) *MockServiceAuthClient_RequireScopes_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockServiceAuthClient_RequireScopes_Call) RunAndReturn(run func(required Scopes) gin.HandlerFunc) *MockServiceAuthClient_RequireScopes_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuthHeader provides a mock function for the type MockServiceAuthClient
func (_mock *MockServiceAuthClient) SetAuthHeader(ctx context.Context, req *http.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceAuthClient_SetAuthHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthHeader'
type MockServiceAuthClient_SetAuthHeader_Call struct {
	*mock.Call
}

// SetAuthHeader is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *MockServiceAuthClient_Expecter) SetAuthHeader(ctx interface{}, req interface{}) *MockServiceAuthClient_SetAuthHeader_Call {
	return &MockServiceAuthClient_SetAuthHeader_Call{Call: _e.mock.On("SetAuthHeader", ctx, req)}
}

func (_c *MockServiceAuthClient_SetAuthHeader_Call) Run(run func(ctx context.Context, req *http.Request)) *MockServiceAuthClient_SetAuthHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceAuthClient_SetAuthHeader_Call) Return(err error) *MockServiceAuthClient_SetAuthHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceAuthClient_SetAuthHeader_Call) RunAndReturn(run func(ctx context.Context, req *http.Request) error) *MockServiceAuthClient_SetAuthHeader_Call {
	_c.Call.Return(run)
	return _c
}
