// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenGetter creates a new instance of MockTokenGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGetter {
	mock := &MockTokenGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGetter is an autogenerated mock type for the TokenGetter type
type MockTokenGetter struct {
	mock.Mock
}

type MockTokenGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGetter) EXPECT() *MockTokenGetter_Expecter {
	return &MockTokenGetter_Expecter{mock: &_m.Mock}
}

// GetAuthToken provides a mock function for the type MockTokenGetter
func (_mock *MockTokenGetter) GetAuthToken(ctx context.Context) (*string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthToken")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGetter_GetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthToken'
type MockTokenGetter_GetAuthToken_Call struct {
	*mock.Call
}

// GetAuthToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenGetter_Expecter) GetAuthToken(ctx interface{}) *MockTokenGetter_GetAuthToken_Call {
	return &MockTokenGetter_GetAuthToken_Call{Call: _e.mock.On("GetAuthToken", ctx)}
}

func (_c *MockTokenGetter_GetAuthToken_Call) Run(run func(ctx context.Context)) *MockTokenGetter_GetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGetter_GetAuthToken_Call) Return(s *string, err error) *MockTokenGetter_GetAuthToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGetter_GetAuthToken_Call) RunAndReturn(run func(ctx context.Context) (*string, error)) *MockTokenGetter_GetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuthHeader provides a mock function for the type MockTokenGetter
func (_mock *MockTokenGetter) SetAuthHeader(ctx context.Context, req *http.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenGetter_SetAuthHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthHeader'
type MockTokenGetter_SetAuthHeader_Call struct {
	*mock.Call
}

// SetAuthHeader is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *MockTokenGetter_Expecter) SetAuthHeader(ctx interface{}, req interface{}) *MockTokenGetter_SetAuthHeader_Call {
	return &MockTokenGetter_SetAuthHeader_Call{Call: _e.mock.On("SetAuthHeader", ctx, req)}
}

func (_c *MockTokenGetter_SetAuthHeader_Call) Run(run func(ctx context.Context, req *http.Request)) *MockTokenGetter_SetAuthHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenGetter_SetAuthHeader_Call) Return(err error) *MockTokenGetter_SetAuthHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenGetter_SetAuthHeader_Call) RunAndReturn(run func(ctx context.Context, req *http.Request) error) *MockTokenGetter_SetAuthHeader_Call {
	_c.Call.Return(run)
	return _c
}
